### ISSUE TITLE
Tutor Feedback for v1.2

### ISSUE THREAD

**Issue by FongYuan** [CS2103-AY1819S1-F10-2/main#117]
Source: https://github.com/nus-cs2103-AY1819S1/addressbook-level4/pull/54#pullrequestreview-166788049

User Guide:
- [x] Few commands refer to the index, while others refer to load id. Are they the same? Use uniformly as interchanging may confuse the user. @prokarius 

Developer Guide:
- [x] Remove the second class diagram under Model component or match it to your class diagram. @FongYuan
- [x] Can remove section 3.2 [Proposed] Data Encryption @FongYuan
- [x] Include UML diagrams for Return a Loan features @prokarius 
- [x] Include UML diagrams for Bicycle Management features @FongYuan
- [x] Can remove Appendix A and other unnecessary details from dev guide that refer to AB-4 @FongYuan
- [x] Limit each use case step to have a single operation and not a sequence of operations. @FongYuan
- [x] Use the right quotes in punctuation @FongYuan
- [x] Hide private information feature doesn't involve the Logic component? Better to include sequence diagrams with in component interactions. @Kelly9373 
- Not enough new/updated UML diagrams to give feedback on. Please try to add more soon.

Overall:
- Draw sequence diagrams for the sequence of steps involved in the execution of command. Keep in mind, however, that we discourage low level diagrams that span multiple components. Try to draw diagrams at multiple levels: one that shows component level interactions and others shown low level interactions within one components.
- Catch up on the documentation of UML diagrams.
- Let's push the product towards a user-testable state by v1.3

**Comment by FongYuan** [comment]
Two tasks are not ticked yet. Please do not close this issue prematurely.

**Comment by prokarius** [comment]
Settled as of 31st October.
