### ISSUE TITLE
Writing user stories in developer guide

### ISSUE THREAD

**Issue by prokarius** [CS2103-AY1819S1-F10-2/main#41]
In the previous progress report, the lack of user stories in our user guide was pointed out.

We will use this issue to populate the user guide with user stories.

**Comment by wn96** [comment]
Please do not capitalise each word in the commit message.

**Comment by prokarius** [comment]
Noted and Edited.

**Comment by FongYuan** [comment]
User stories have been added to the dev guide.
https://github.com/CS2103-AY1819S1-F10-2/main/pull/45
