### ISSUE TITLE
Add all data fields to the Loan class

### ISSUE THREAD

**Issue by FongYuan** [CS2103-AY1819S1-F10-2/main#66]
- [x] ID
- [x] loanerName
- [x] loanerIC
- [x] loanerPhone
- [x] loanerEmail
- [ ] remove Address
- [x] loanedBike
- [x] loanStartTime
- [x] loanEndTime
- [x] loanRate

**Comment by FongYuan** [comment]
We discussed before (during recess week) that it would be easier to implement the fields as-is, as there isn't much point in tracking a person/customer class in particular.

Though I'm not stopping you if you want to do it.

**Comment by prokarius** [comment]
Include LoanEndTime (Type Optional<LoanTime>) as well.

**Comment by FongYuan** [comment]
Good consideration. Do you think it should be an absolute time (e.g. "1800" for 6 pm), or should it be a loanDuration instead? I'm thinking the latter is easier to key in. But the former prevents cases like the loan ending at 6:03 pm for example.

**Comment by prokarius** [comment]
Refer to PR #133 and #105 for loanStartTime, loanEndTime and loanStatus. 

Also, this issue is duplicated in #103.

**Comment by FongYuan** [comment]
The final remaining task, "Remove Address", has its own issue here: https://github.com/CS2103-AY1819S1-F10-2/main/issues/89
I will close this issue and use that issue to track it.
